### ISSUE TITLE
i face this error in the discord :: pls help 

### ISSUE THREAD

**Issue by simpleman000** [NameNami/OTP-Bot-2nd-version#1]
The application did not respond
when i use bot V2

the bot v1 works 
the bot v 2 said The application did not respond

**Comment by Warnings225** [comment]
Yea true, V1 works fine but this one when i use .call nothing happens

**Comment by simpleman000** [comment]
[](url)

**Comment by simpleman000** [comment]
> Yea true, V1 works fine but this one when i use .call nothing happens

The application did not respond ? in the discord there is some mistake in devolpment ! 
we will see the owner respond
